[Prefix="VHACD::"]
interface VHACD {
  void VHACD();
  boolean Compute(float[] points, unsigned long nPoints, unsigned long[] triangles, unsigned long nTriangles, [Const, Ref]Parameters params);
  unsigned long GetNConvexHulls();
  void GetConvexHull(unsigned long index, [Ref]ConvexHull ch);
  void Cancel();
  void Clean();
  void Release();
};

[Prefix="VHACD::IVHACD::"]
interface Parameters {
  void Parameters();
    attribute double m_concavity;
    attribute double m_alpha;
    attribute double m_beta;
    attribute double m_minVolumePerCH;
    attribute unsigned long m_resolution;
    attribute unsigned long m_maxNumVerticesPerCH;
    attribute unsigned long m_planeDownsampling;
    attribute unsigned long m_convexhullDownsampling;
    attribute unsigned long m_pca;
    attribute unsigned long m_mode;
    attribute unsigned long m_convexhullApproximation;
	attribute unsigned long	m_maxConvexHulls;
};

[Prefix="VHACD::IVHACD::"]
interface ConvexHull {
  void ConvexHull();
  readonly attribute double[] m_points;
  readonly attribute unsigned long[] m_triangles;
  readonly attribute unsigned long m_nPoints;
  readonly attribute unsigned long m_nTriangles;
};
